# Form implementation generated from reading ui file 'ui/LoginForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(523, 330)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../images/csuLogo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        LoginDialog.setWindowIcon(icon)
        self.loginButton = QtWidgets.QPushButton(parent=LoginDialog)
        self.loginButton.setGeometry(QtCore.QRect(370, 250, 93, 28))
        self.loginButton.setObjectName("loginButton")
        self.usernameLabel = QtWidgets.QLabel(parent=LoginDialog)
        self.usernameLabel.setGeometry(QtCore.QRect(250, 80, 91, 16))
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(parent=LoginDialog)
        self.passwordLabel.setGeometry(QtCore.QRect(250, 150, 91, 16))
        self.passwordLabel.setObjectName("passwordLabel")
        self.csuLogo = QtWidgets.QLabel(parent=LoginDialog)
        self.csuLogo.setGeometry(QtCore.QRect(30, 80, 171, 171))
        self.csuLogo.setText("")
        self.csuLogo.setPixmap(QtGui.QPixmap("ui\\../images/csuLogo.png"))
        self.csuLogo.setScaledContents(True)
        self.csuLogo.setObjectName("csuLogo")
        self.label = QtWidgets.QLabel(parent=LoginDialog)
        self.label.setGeometry(QtCore.QRect(230, 30, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.statusLabel = QtWidgets.QLabel(parent=LoginDialog)
        self.statusLabel.setGeometry(QtCore.QRect(190, 230, 171, 20))
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.usernameField = QtWidgets.QLineEdit(parent=LoginDialog)
        self.usernameField.setGeometry(QtCore.QRect(250, 100, 221, 31))
        self.usernameField.setObjectName("usernameField")
        self.passwordField = QtWidgets.QLineEdit(parent=LoginDialog)
        self.passwordField.setGeometry(QtCore.QRect(250, 170, 221, 31))
        self.passwordField.setObjectName("passwordField")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Login"))
        self.loginButton.setText(_translate("LoginDialog", "Login"))
        self.usernameLabel.setText(_translate("LoginDialog", "Username"))
        self.passwordLabel.setText(_translate("LoginDialog", "Password"))
        self.label.setText(_translate("LoginDialog", "LOGIN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec())
