# Form implementation generated from reading ui file 'ui/RegisterForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterDialog(object):
    def setupUi(self, RegisterDialog):
        RegisterDialog.setObjectName("RegisterDialog")
        RegisterDialog.resize(523, 330)
        self.passwordLabel = QtWidgets.QLabel(parent=RegisterDialog)
        self.passwordLabel.setGeometry(QtCore.QRect(250, 150, 91, 16))
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordField = QtWidgets.QTextEdit(parent=RegisterDialog)
        self.passwordField.setGeometry(QtCore.QRect(250, 170, 221, 31))
        self.passwordField.setObjectName("passwordField")
        self.usernameLabel = QtWidgets.QLabel(parent=RegisterDialog)
        self.usernameLabel.setGeometry(QtCore.QRect(250, 80, 91, 16))
        self.usernameLabel.setObjectName("usernameLabel")
        self.csuLogo = QtWidgets.QLabel(parent=RegisterDialog)
        self.csuLogo.setGeometry(QtCore.QRect(30, 80, 171, 171))
        self.csuLogo.setText("")
        self.csuLogo.setPixmap(QtGui.QPixmap("ui\\../images/csuLogo.png"))
        self.csuLogo.setScaledContents(True)
        self.csuLogo.setObjectName("csuLogo")
        self.usernameField = QtWidgets.QTextEdit(parent=RegisterDialog)
        self.usernameField.setGeometry(QtCore.QRect(250, 100, 221, 31))
        self.usernameField.setObjectName("usernameField")
        self.registerButton = QtWidgets.QPushButton(parent=RegisterDialog)
        self.registerButton.setGeometry(QtCore.QRect(370, 250, 93, 28))
        self.registerButton.setObjectName("registerButton")
        self.label_2 = QtWidgets.QLabel(parent=RegisterDialog)
        self.label_2.setGeometry(QtCore.QRect(220, 40, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.statusLabel = QtWidgets.QLabel(parent=RegisterDialog)
        self.statusLabel.setGeometry(QtCore.QRect(230, 230, 55, 16))
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.roleComboBox = QtWidgets.QComboBox(parent=RegisterDialog)
        self.roleComboBox.setGeometry(QtCore.QRect(250, 240, 73, 22))
        self.roleComboBox.setObjectName("roleComboBox")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.roleLabel = QtWidgets.QLabel(parent=RegisterDialog)
        self.roleLabel.setGeometry(QtCore.QRect(250, 220, 91, 16))
        self.roleLabel.setObjectName("roleLabel")

        self.retranslateUi(RegisterDialog)
        QtCore.QMetaObject.connectSlotsByName(RegisterDialog)

    def retranslateUi(self, RegisterDialog):
        _translate = QtCore.QCoreApplication.translate
        RegisterDialog.setWindowTitle(_translate("RegisterDialog", "Register"))
        self.passwordLabel.setText(_translate("RegisterDialog", "Password"))
        self.usernameLabel.setText(_translate("RegisterDialog", "Username"))
        self.registerButton.setText(_translate("RegisterDialog", "Register"))
        self.label_2.setText(_translate("RegisterDialog", "REGISTER"))
        self.roleComboBox.setItemText(0, _translate("RegisterDialog", "Admin"))
        self.roleComboBox.setItemText(1, _translate("RegisterDialog", "User"))
        self.roleLabel.setText(_translate("RegisterDialog", "Role"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterDialog = QtWidgets.QDialog()
    ui = Ui_RegisterDialog()
    ui.setupUi(RegisterDialog)
    RegisterDialog.show()
    sys.exit(app.exec())
